# Generated by Django 4.2.7 on 2023-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=18, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=18, verbose_name='Soy isim')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
    ]
