# Generated by Django 4.2.7 on 2023-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='TeamProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=70, verbose_name='Proje Başlığı')),
                ('project_description', models.TextField(verbose_name='Proje Açıklaması')),
            ],
            options={
                'verbose_name': 'team project',
                'verbose_name_plural': 'team projects',
            },
        ),
    ]
