# Generated by Django 4.2.7 on 2023-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_log_teamprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
    ]
